// TikTok service facade. The underlying Tauri transport remains in the
// shared API module so existing command names and payloads stay unchanged.
export {
  clearSessionLog,
  getCurrentRunStatus,
  getSchedulerHealth,
  getSchedulerProcessStatus,
  getSqliteStatus,
  getStderrChunk,
  getStdoutChunk,
  loadCommentPools,
  loadConfig,
  queryActionLogs,
  queryFypStats,
  queryFypVideoViews,
  queryProfileStatsDetail,
  queryProfileStatsHistory,
  queryProfileStatsLatest,
  queryProfileStatsSummary,
  querySchedulerJobRuns,
  queryTargetEngagements,
  queryTargetFollows,
  queryTargetStats,
  queryTargetWatermarks,
  resetTargetWatermark,
  runGmailSetup,
  runPlatformTask,
  runTikTokRegister,
  runTikTokRegisterBatch,
  saveCommentPools,
  saveFypSettings,
  saveSchedulerSettings,
  saveTargetEngagementSettings,
  startScheduler,
  stopScheduler,
  tailSessionLog,
} from '../../../services/api'
